"""Flask Moment

Revision ID: 3132c7d50764
Revises: None
Create Date: 2016-03-05 19:42:22.125000

"""

# revision identifiers, used by Alembic.
revision = '3132c7d50764'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('created_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'created_time')
    ### end Alembic commands ###
