"""another migrate

Revision ID: 7d705550d1c2
Revises: None
Create Date: 2016-02-18 10:45:59.253000

"""

# revision identifiers, used by Alembic.
revision = '7d705550d1c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(length=64), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('lis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lis_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_body'), 'tasks', ['body'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_body'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('lists')
    ### end Alembic commands ###
