"""Relationship addition

Revision ID: ae1c6b2d5b85
Revises: cdd468be05ed
Create Date: 2016-02-21 18:18:55.247000

"""

# revision identifiers, used by Alembic.
revision = 'ae1c6b2d5b85'
down_revision = 'cdd468be05ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lists', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'author_id')
    ### end Alembic commands ###
